site_name: Iut Services Docs
site_url: https://iut-services-docs.com/
nav:
  - Team: team.md
  - Home: index.md
  - Répertoire: directory.md
  - Connexion: login.md
  - Services: services.md
  - Répertoire: directory.md
  - Paramètres : parametres.md
theme: readthedocs
markdown_extensions: 
  - admonition
plugins:
  - search
  - with-pdf:
      cover_title: "Iut Services"
      cover_subtitle: "Documentation du projet Iut Services"
      author: "Anthony ELUECQUE, Lucie LE FUR, Laetitïa BERNARD, Houssam CUMZAIN"
      copyright: "2023"
