site_name: Iut Services Docs
site_url: https://iut-services-docs.com/
nav:
  - Team: team.md
  - Home: index.md
  - Répertoire: directory.md
  - Connexion: login.md
  - Services: services.md
  - Paramètres : parametres.md
theme: readthedocs
markdown_extensions: 
  - admonition